std = "min"
cache = "true"

-- Add your own globals here
globals = {
	"Dune",
}

-- Blightmud internals
read_globals = {
	core = {
		fields = {
			enable_protocol = {},
			disable_protocol = {},
			on_protocol_enabled = {},
			subneg_recv = {},
			subneg_send = {},
			store = {},
			read = {},
			exec = {},
		},
	},
	blight = {
		fields = {
			connect = {},
			reset = {},
			load = {},
			output = {},
			mud_output = {},
			bind = {},
			unbind = {},
			ui = {},
			send = {},
			send_bytes = {},
			user_input = {},
			debug = {},
			store = {},
			read = {},
			start_log = {},
			stop_log = {},
			add_alias = {},
			enable_alias = {},
			remove_alias = {},
			get_aliases = {},
			clear_aliases = {},
			add_trigger = {},
			enable_trigger = {},
			remove_trigger = {},
			get_triggers = {},
			clear_triggers = {},
			add_timer = {},
			get_timer_ids = {},
			clear_timers = {},
			status_height = {},
			status_line = {},
			on_connect = {},
			on_disconnect = {},
			version = {},
			gag = {},
		},
	},
	tts = {
		fields = {
			speak = {},
			speak_direct = {},
			stop = {},
			gag = {},
			enable = {},
			set_rate = {},
			change_rate = {},
			echo_keypresses = {},
			step_back = {},
			step_forward = {},
			scan_back = {},
			scan_forward = {},
			scan_input_back = {},
			scan_input_forward = {},
			step_begin = {},
			step_end = {},
		},
	},
	gmcp = {
		fields = {
			on_ready = {},
			register = {},
			receive = {},
			send = {},
			echo = {},
		},
	},
	msdp = {
		fields = {
			list = {},
			send = {},
			report = {},
			unreport = {},
			set = {},
			get = {},
			register = {},
			on_ready = {},
		},
	},
	json = {
		fields = {
			encode = {},
			decode = {},
		},
	},
	trigger = {
		fields = {
			add = {},
			get = {},
			add_group = {},
			get_group = {},
			remove = {},
			clear = {},
		}
	},
	alias = {
		fields = {
			add = {},
			add_group = {},
			get = {},
			get_group = {},
			remove = {},
			clear = {},
		}
	},
	cformat = {},

	C_RESET = {},
	C_BLACK = {},
	C_RED = {},
	C_GREEN = {},
	C_YELLOW = {},
	C_BLUE = {},
	C_MAGENTA = {},
	C_CYAN = {},
	C_WHITE = {},
	BG_BLACK = {},
	BG_RED = {},
	BG_GREEN = {},
	BG_YELLOW = {},
	BG_BLUE = {},
	BG_MAGENTA = {},
	BG_CYAN = {},
	BG_WHITE = {},
	C_BBLACK = {},
	C_BRED = {},
	C_BGREEN = {},
	C_BYELLOW = {},
	C_BBLUE = {},
	C_BMAGENTA = {},
	C_BCYAN = {},
	C_BWHITE = {},
	BG_BBLACK = {},
	BG_BRED = {},
	BG_BGREEN = {},
	BG_BYELLOW = {},
	BG_BBLUE = {},
	BG_BMAGENTA = {},
	BG_BCYAN = {},
	BG_BWHITE = {},
}
